define([
    	"dojo/_base/declare"
], function(dojo_declare){
	
var _Constants = dojo_declare("ier._Constants", null, {
	ApplicationPlugin: "IERApplicationPlugin",
	IERDesktop : "IERDesktop",
	IER_RootHelpLink: "http://publib.boulder.ibm.com/infocenter/p8docs/v5r1m0",
	PostEncoding: "application/x-www.form-urlencoded",
	NexusAdminClientId : "ecmClientAdmin",
	DispositionEventType : "ierDispositionTriggerEventType",
	IER_COGNOS_REPORT_URL: "${0}?b_action=cognosViewer&ui.action=run&run.prompt=false&ui.object=${1}/" +
	"package[@name='${2} package']/report[@name='${2}']&p_rpt_job_id=${3}&cv.header=false&ui=h1h2h3",
	HelpContextUrl: "/com.ibm.ier.help.doc/",
	DEFAULT_COGNOS_REPORT_PATH: "/content/folder[@name='IERReport']",

	//actions
	Action_AddAction : "IERAddDispositionAction",
	Action_AddFilePlan : "IERAddFilePlan",
	Action_AddHold : "IERAddHold",
	Action_AddLocation : "IERAddLocation",
	Action_AddRecordType : "IERAddRecordType",
	Action_AddTransferMapping : "IERAddTransferMapping",
	Action_AddEventTrigger : "IERAddEventTrigger",
	Action_AddNamingPattern : "IERAddNamingPattern",
	Action_AddRecordCategory : "IERAddRecordCategory",
	Action_AddRecordFolder : "IERAddRecordFolder",
	Action_AddRecordVolume : "IERAddRecordVolume",
	Action_Properties : "IERProperties",
	Action_Refresh : "IERRefresh",
	Action_AddDispositionSchedule : "IERAddDispositionSchedule",
	Action_RunReport : "IERRunReport",
	Action_AddReportDefinition : "IERAddReportDefinition",
	Action_Delete : "IERDelete",
	Action_ScheduleReport : "IERScheduleReport",
	Action_ScheduleDispositionSweep : "IERScheduleDispositionSweep",
	Action_ScheduleHoldSweep : "IERScheduleHoldSweep",
	Action_ScheduleDDContainerConversion : "IERScheduleConversionToDDContainers",
	
	//Action types for disposition actions
	ActionType_Review : "1",
	ActionType_Export : "2",
	ActionType_Transfer : "3",
	ActionType_Destroy : "4",
	ActionType_InterimTransfer : "5",
	ActionType_Cutoff : "6",
	ActionType_VitalReview : "7",
	ActionType_AutoDestroy : "8",
	
	//attributes
	Attribute_RepositoryType : "ierRepositoryType",
	Attribute_Status : "status",
	Attribute_Type : "type",
	
	//class names
	ClassName_Container : "RMFolder",
	ClassName_CustomObject : "CustomObject",
	ClassName_DispositionAction : "Action1",
	ClassName_DispositionSchedule : "DisposalSchedule",
	ClassName_DispositionTrigger : "DisposalTrigger",
	ClassName_Document : "Document",
	ClassName_ElectronicRecordFolder : "ElectronicRecordFolder",
	ClassName_ElectronicRecord : "ElectronicRecordInfo",
	ClassName_Location : "Location",
	ClassName_PhysicalRecord : "Markers",
	ClassName_Email : "Email",
	ClassName_EmailRecord : "EmailRecordInfo",
	ClassName_FilePlan : "ClassificationScheme",
	ClassName_HybridRecordFolder : "HybridRecordFolder",
	ClassName_Link : "Relation",
	ClassName_NamingPattern : "Pattern",
	ClassName_PhysicalRecordFolder : "PhysicalRecordFolder",
	ClassName_PhysicalContainer : "Box",
	ClassName_Record : "RecordInfo",
	ClassName_ReportDefinition : "RMReportDefinition",
	ClassName_RecordType : "RecordType",
	ClassName_RecordCategory : "RecordCategory",
	ClassName_RecordsManagementFolder : "ClassificationSchemes",
	ClassName_ReportHold : "ReportHoldings",
	ClassName_TransferMapping : "RMTransferMapping",
	ClassName_Transcript: "Transcript",
	ClassName_SystemConfiguration: "SystemConfiguration",
	ClassName_Volume : "Volume",
	ClassName_Hold : "RecordHold",
	ClassName_RecordFolder : "RecordFolder",
	ClassName_WorkflowDefinition : "WorkflowDefinition",
	
	//datatype
	DataType_Group : "xs:group",
	DataType_User : "xs:user",
	DataType_String : "xs:string",
	DataType_DateTime : "xs:timestamp",
	DataType_Cardinality_LIST : "LIST",
	DataType_Object : "xs:object",
	
	//entity types
	EntityType_ElectronicRecord : "301",
	EntityType_ElectronicRecordFolder : "105",
	EntityType_EmailRecord : "302",
	EntityType_DispositionAction : "200",
	EntityType_DispositionSchedule : "201",
	EntityType_DispositionTrigger : "203",
	EntityType_FilePlan : "100",
	EntityType_Hold : "216",
	EntityType_HybridRecordFolder : "108",
	EntityType_Link : "400",
	EntityType_Location : "215",
	EntityType_NamingPattern : "205",
	EntityType_PDFRecord : "305",
	EntityType_PhysicalContainer : "106",
	EntityType_PhysicalRecord : "303",
	EntityType_PhysicalRecordFolder : "110",
	EntityType_Record : "300",
	EntityType_RecordCategory : "101",
	EntityType_RecordFolder : "102",
	EntityType_RecordType : "214",
	EntityType_ReportDefinition : "207",
	EntityType_TransferMapping : "804",
	EntityType_Volume : "103",
	EntityType_Container : "1100",
	EntityType_ContainerAndRecord : "3001100",

	//event type
	EventType_PredefinedDateTrigger: "1",
	EventType_ExternalEventTrigger: "2",
	EventType_InternalEventTrigger: "3",
	EventType_RecurringEventTrigger: "4",
	
	//Features
	Feature_IERConfigure : "IERConfigure",
	Feature_IERBrowseFilePlan : "IERBrowseFilePlan",
	Feature_IERSearch : "IERSearch",
	Feature_IERFavorites : "IERFavorites",
	Feature_IERReports : "IERReports",
	Feature_IERAdmin : "IERAdmin",
	Feature_IERTasks : "IERTasks",
	FeaturePane_IERBrowseFilePlan : "IERBrowseFilePlan_popup",
	
	//ids
	Id_RecordsManagementFolder : "{56EA3C34-4084-4709-BBE6-A1B9E35C3E7B}",
	Id_FilePlanFolder : "{7F29139B-04E0-442F-9B85-C71EA4988375}", //The FilePlan folder Id
	Id_RootFolder : "{0F1E2D3C-4B5A-6978-8796-A5B4C3D2E1F0}",
	Id_ActionTypeChoiceList : "{56C6D10C-05FB-4CBD-9872-55B3F5DAFC2E}",
	Id_ReviewDecisionChoiceList : "{22F5F075-51D2-4D44-9235-05037611821F}",
	
	DocId_FilePlanFolder : "ClassificationScheme,null,{7F29139B-04E0-442F-9B85-C71EA4988375}",
	Id_ReportDefintionFolder : "{5E8189C9-C2E7-43BB-B5AF-EB5E69CAA543}",
	
	//Mimetype
	Mimetype_ElectronicRecord : "application/x-filenet-rm-electronicrecord",
	Mimetype_EmailRecord : "application/x-filenet-rm-emailrecord",
	Mimetype_PhysicalRecord : "application/x-filenet-rm-physicalrecord",
	Mimetype_ExternalDocument : "application/x-filenet-external",
	
	//MenuType
	MenuType_ContentListToolbar : "ContentListToolbar",
	MenuType_IERFilePlanContextMenu : "IERFilePlanContextMenuType",
	MenuType_IERFilePlanConfigureContextMenu : "IERFilePlanConfigureContextMenuType",
	MenuType_IERRecordCategoryContextMenu : "IERRecordCategoryContextMenuType",
	MenuType_IERPhysicalBoxHybridRecordFolderContextMenu : "IERPhysicalBoxHybridRecordFolderContextMenuType",
	MenuType_IERElectronicRecordFolderContextMenu : "IERElectronicRecordFolderContextMenuType",
	MenuType_IERVolumeContextMenu : "IERVolumeContextMenuType",
	MenuType_IERPhysicalRecordContextMenu : "IERPhysicalRecordContextMenuType",
	MenuType_IERElectronicRecordContextMenu : "IERElectronicRecordContextMenuType",
	MenuType_IERMultipleContainerAndRecordContextMenu : "IERMultipleContainerAndRecordContextMenuType",
	MenuType_IERMultipleContainerContextMenu : "IERMultipleContainerContextMenuType",
	MenuType_IERMultipleRecordContextMenu : "IERMultipleRecordContextMenuType",
	MenuType_IERCustomObjectsContextMenu : "IERCustomObjectContextMenuType",
	MenuType_IERPropertiesOnlyCustomObjectsContextMenu : "IERPropertiesOnlyCustomObjectContextMenuType",
	MenuType_IERMultipleCustomObjectsContextMenu : "IERMultipleCustomObjectsContextMenuType",
	MenuType_IERPlaceOnHoldContextMenu : "IERPlaceOnHoldContextMenuType",
	MenuType_IERRemoveHoldContextMenu : "IERRemoveHoldContextMenuType",
	MenuType_IERConfigureFlyoutToolbarMenu : "IERConfigureFlyoutToolbarMenuType",
	MenuType_IERActionsConfigureToolbarMenu : "IERActionsConfigureToolbarMenuType",
	MenuType_IERDispositionSchedulesConfigureToolbarMenu : "IERDispositionSchedulesConfigureToolbarMenuType",
	MenuType_IERFilePlansConfigureToolbarMenu : "IERFilePlansConfigureToolbarMenuType",
	MenuType_IERHoldsConfigureToolbarMenu : "IERHoldsConfigureToolbarMenuType",
	MenuType_IERHoldsConfigureContextMenu : "IERHoldsConfigureContextMenuType",
	MenuType_IERLocationsConfigureToolbarMenu : "IERLocationsConfigureToolbarMenuType",
	MenuType_IERRecordTypesConfigureToolbarMenu : "IERRecordTypesConfigureToolbarMenuType",
	MenuType_IERReportDefinitionsConfigureToolbarMenu : "IERReportDefinitionsConfigureToolbarMenuType",
	MenuType_IERReportDefinitionsConfigureContextMenu : "IERReportDefinitionsConfigureContextMenuType",
	MenuType_IERTriggersConfigureToolbarMenu : "IERTriggersConfigureToolbarMenuType",
	MenuType_IERTranferMappingsConfigureToolbarMenu : "IERTransferMappingsConfigureToolbarMenuType",
	MenuType_IERNamingPatternsConfigureToolbarMenu : "IERNamingPatternsConfigureToolbarMenuType",
	MenuType_IERReportResultsContextMenu : "IERReportResultActionMenuType",
	MenuType_IERViewEntitiesOnHoldContextMenu : "IERViewEntitiesOnHoldContextMenuType",
	MenuType_IERReportsCompletedTaskContextMenu : "IERReportsCompletedTaskContextMenuType",
	MenuType_IERCompletedTaskContextMenu : "IERCompletedTaskContextMenuType",
	MenuType_IERFailedTaskContextMenu : "IERFailedTaskContextMenuType",
	MenuType_IERFailedRecurringTaskContextMenu: "IERFailedRecurringTaskContextMenuType",
	MenuType_IERScheduledTaskContextMenu : "IERScheduledTaskContextMenuType",
	MenuType_IERScheduledRecurringTaskContextMenu : "IERScheduledRecurringTaskContextMenuType",
	MenuType_IERDisabledRecurringTaskContextMenu : "IERDisabledRecurringTaskContextMenuType",
	MenuType_IERInProgressTaskContextMenu : "IERInProgressTaskContextMenuType",
	MenuType_IERInProgressTaskInstanceContextMenu : "IERInProgressTaskInstanceContextMenuType",
	MenuType_IERScheduledTaskInstanceContextMenu : "IERScheduledTaskInstanceContextMenuType",
	MenuType_IERFailedTaskInstanceContextMenu : "IERFailedTaskInstanceContextMenuType",
	MenuType_IERReportsCompletedTaskInstanceContextMenu : "IERReportsCompletedTaskInstanceContextMenuType",
	MenuType_IERCompletedTaskInstanceContextMenu : "IERCompletedTaskInstanceContextMenuType",
	MenuType_IERCompletedRecurringTaskContextMenu : "IERCompletedRecurringTaskContextMenuType",
	MenuType_IERFavoriteRecordCategoryContextMenu : "IERFavoriteRecordCategoryContextMenuType",
	MenuType_IERFavoriteElectronicRecordFolderContextMenu : "IERFavoriteElectronicRecordFolderContextMenuType", 
	MenuType_IERFavoritePhysicalRecordFolderContextMenu : "IERFavoritePhysicalRecordFolderContextMenuType",
	MenuType_IERFavoriteVolumeContextMenu : "IERFavoriteVolumeContextMenuType",
	MenuType_IERFavoriteElectronicRecordContextMenu : "IERFavoriteElectronicRecordContextMenuType",
	MenuType_IERFavoritePhysicalRecordContextMenu : "IERFavoritePhysicalRecordContextMenuType",
	MenuType_IERSearchElectronicRecordContextMenu : "IERSearchElectronicRecordContextMenuType",
	MenuType_IERSearchPhysicalRecordContextMenu : "IERSearchPhysicalRecordContextMenuType",
	MenuType_IERBrowseFilePlanToolbarMenu : "IERBrowseFilePlanToolbarMenuType",
	MenuType_IERMultipleTasksContextMenu: "IERMultipleTasksContextMenuType",
	MenuType_IERHoldConditionContainerContextMenu: "IERHoldConditionContainerContextMenuType",
	MenuType_IERHoldConditionRecordContextMenu: "IERHoldConditionRecordContextMenuType",

	//params
	Param_ArchiveProperties : "archive_criterias",
	Param_CE_EJB_URL : "ceEJBURL",
	Param_ClassName : "ier_className",
	Param_Conditions : "ier_conditions",
	Param_ContainerId : "ier_containerid",
	Param_ContainerName : "containerName",
	Param_ContinuationData : "continuationData",
	Param_DatamodelType : "datamodelType",
	Param_Desktop : "desktop",
	Param_Description : "template_desc",
	Param_Description2: "description",
	Param_DestinationContainer : "ier_destinationContainer",
	Param_DispositionScheduleId : "ier_dispositionScheduleId",
	Param_DispositionAggregationType: "ier_aggregationType",
	Param_DispositionCutoffAction: "ier_dispositionCutoffAction",
	Param_DispositionEventOffset: "ier_dispositionEventOffset",
	Param_DispositionEventCutoffBase : "ier_dispositionEventCutoffBase",
	Param_DocId : "ier_docId",
	Param_Dynamic_Hold_Task : "ier_dynamic_hold_task",
	Param_EmailAddress: "emailAddress",
	Param_EndTime : "endTime",
	Param_EntityId : "ier_entityId",
	Param_EntityType : "ier_entityType",
	Param_Entities : "entities",
	Param_EventType : "ier_eventType",
	Param_FilterString : "ier_filterString",
	Param_Id : "ier_id",
	Param_FilePlanId : "ier_fileplanId",
	Param_FilePlanRepositoryId : "ier_fileplanRepositoryId",
	Param_FilePlanRepositoryNexusId : "ier_fileplanRepositoryNexusId",
	Param_FilePlanRepositoryFolderLocation : "ier_fileplanRepositoryFolderLocation",
	Param_HoldId : "ier_holdId",
	Param_Holdables : "ier_holdables",
	Param_Holds : "ier_holds",
	Param_IsRecurring: "isRecurring",
	Param_Label : "template_name",
	Param_LinkClass : "ier_linkClass",
	Param_LinkReason : "ier_linkReasonForExtract",
	Param_LinkedRecordId : "ier_linkedRecordId",
	Param_LocationId : "ier_locationId",
	Param_Name : "template_name",
	Param_Name2: "name",
	Param_NameFilter : "nameFilter",
	Param_NumberOfDocuments : "ier_ndocs",
	Param_OrderBy: "ier_orderBy",
	Param_OrderByDescending : "order_descending",
	Param_QuickSearchMoreType : "ier_quickSearchMoreType",
	Param_QuickSearchQueryString : "ier_quickSearchQueryString",
	Param_QuickSearchStartingPoint : "ier_quickSearchStartingPoint",
	Param_Parent : "parent",
	Param_PluginConfiguration : "ierPluginConfiguration",
	Param_P8RepositoryId : "ier_p8RepositoryId",
	Param_P8RepositoryGuid : "p8RepositoryGuid",
	Param_RecordId : "ier_recordId",
	Param_RepeatCycle : "repeatCycle",
	Param_ReportDefinitionProperties : "ier_reportdefintionProperties",
	Param_ReportId : "ier_reportid",
	Param_ReportName : "ier_reportName",
	Param_ReportTitle : "ier_reportTitle",
	Param_ReportResultsId : "ier_reportResultsId",
	Param_ReportResultsIds : "ier_reportResultsIds",
	Param_RepositoryId : "repositoryId",
	Param_Repository : "repository",
	Param_ParameterList : "parameterList",
	Param_ParentFolderId : "ier_parentFolderId",
	Param_ParentClassName : "parentClassName",
	Param_Password : "password",
	Param_PatternId : "ier_patternId",
	Param_PatternLevels : "ier_patternLevels",
	Param_PatternString : "ier_patternString",
	Param_Permissions: "ier_permissions",
	Param_Properties : "criterias",
	Param_PropertyName : "ier_propertyName",
	Param_ReasonForClose : "ier_reasonforclose",
	Param_ReasonForMove : "ier_reasonformove",
	Param_ReasonForRelocate : "ier_reasonforrelocate",
	Param_RecordClass : "ier_recordClass",
	Param_RepositoryIds : "ier_repositoryIds",
	Param_RetentionTriggerPropertyName: "retentionTriggerPropertyName",
	Param_RetentionPeriod: "retentionPeriod",
	Param_RetentionPeriodYears: "retentionPeriodYears",
	Param_RetentionPeriodMonths: "retentionPeriodMonths",
	Param_RetentionPeriodDays: "retentionPeriodDays",
	Param_RootDownloadLinkURL : "rootDownloadLinkURL",
	Param_SaveInFolderLocation : "ier_saveInFolderLocation",
	Param_SaveInFolderLocationName : "ier_saveInFolderLocationName",
	Param_SaveInRepository : "ier_saveInRepository",
	Param_SchedulePropagationLevel : "schedulePropagationLevel",
	Param_SecurityParentItemId : "ier_securityParentItemId",
	Param_ServerName : "serverName",
	Param_ShowAdditionalColumns : "ier_showAdditionalColumns",
	Param_SortBy : "sortBy",
	Param_SourceContainer : "ier_sourceContainer",
	Param_StartTime : "startTime",
	Param_SQL: "ier_sql",
	Param_SystemConfigurations: "ier_systemConfigurations",
	Param_TableName : "ier_tableName",
	Param_TableNames : "ier_tableNames",
	Param_TaskType : "taskType",
	Param_TaskStatus : "taskStatus",
	Param_TemplateName : "template_name",
	Param_Type: "type",
	Param_UserId : "userId",
	Param_StartDate: "startDate",
	Param_EndDate: "endDate",
	Param_FilterField: "filterField",
	param_FilterActionType: "filterActionType",
	param_FilterStatus: "filterStatus",

	//privileges
	Privilege_FileInFolder : "privFileInFolder",
	Privilege_CanDeclareRecordToContainer : "privCanDeclareRecordToContainer",
	Privilege_CanMoveRecordToContainer : "privCanMoveRecordToContainer",
	Privilege_AddRecordCategory : "privIERAddRecordCategory",
	Privilege_AddRecordFolder : "privIERAddRecordFolder",
	Privilege_TaskUser : "privTaskUserPermission",
	Privilege_TaskAdmin: "privTaskAdminPermission",
	
	//properties
	Property_ActionName : "ActionName",
	Property_ActionType : "ActionType",
	Property_Active : "Active",
	Property_Aggregation : "AGGREGATION",
	Property_Alias : "Alias",
	Property_AllowedRMContainees: "AllowedRMContainees",
	Property_AllowedRMTypes : "AllowedRMTypes",
	Property_AlternateRetentions : "AlternateRetentions",
	Property_ApplicationName : "ApplicationName",
	Property_ApplyToNameOrId : "ApplyToNameOrId",
	Property_AssociatedRecordType : "AssociatedRecordType",
	Property_AssociatedWorkflow : "DefaultWorkflow",
	Property_Barcode : "BarcodeID",
	Property_CC : "CarbonCopy",
	Property_ChargeOutStatus : "ChargeOutStatus",
	Property_ChargeOutTo : "ChargeOutTo",
	Property_ConditionXML : "ConditionXML",
	Property_ContentElementPresent : "ContentElementsPresent",
	Property_CreateDate : "DateCreated",
	Property_CurrentPhaseAction : "CurrentPhaseAction",
	Property_CurrentPhaseDecisionDate : "CurrentPhaseDecisionDate",
	Property_CurrentPhaseReviewDecision : "CurrentPhaseReviewDecision",
	Property_CurrentPhaseExecutionDate : "CurrentPhaseExecutionDate",
	Property_CutoffDate : "CutoffDate",
	Property_CycleYears : "CycleYears",
	Property_CycleMonths : "CycleMonths",
	Property_CycleDays : "CycleDays",
	Property_DateClosed : "DateClosed",
	Property_DateLastModified : "DateLastModified",
	Property_DateOpened : "DateOpened",
	Property_DateTime : "DateTime",
	Property_Description : "Description",
	Property_DispositionSchedule : "DisposalSchedule",
	Property_DispositionScheduleName : "DisposalScheduleName",
	Property_DispositionTriggerName : "DisposalTriggerName",
	Property_DisposalScheduleInheritedFrom: "DisposalScheduleInheritedFrom",
	Property_DispositonAuthority : "AuthorisingStatute",
	Property_DocumentTitle : "DocumentTitle",
	Property_ExternalEventOccurenceDate : "ExternalEventOccurrenceDate",
	Property_EventType : "EventType",
	Property_FilePlanName : "ClassificationSchemeName",
	Property_FolderName : "FolderName",
	Property_Frequency : "ierFrequency",
	Property_From : "From",
	Property_HoldName : "HoldName",
	Property_HoldReason : "HoldReason",
	Property_HoldType : "HoldType",
	Property_IsDynamicHold : "IsDynamicHold",
	Property_Holds : "Holds",
	Property_HomeLocation : "HomeLocation",
	Property_IsDeleted : "IsDeleted",
	Property_Inactive : "Inactive",
	Property_IsVitalRecord : "IsVitalRecord",
	Property_LastModifier : "LastModifier",
	Property_LastSweepDate : "LastSweepDate",
	Property_SweepState : "SweepState",
	Property_LinkName : "LinkName",
	Property_Location : "Location",
	Property_LocationName : "LocationName",
	Property_MethodofDestruction : "MethodofDestruction",
	Property_NamingPattern : "Pattern",
	Property_PatternName : "PatternName",
	Property_PermanentRecordIndicator : "IsPermanentRecord",
	Property_PreventRMEntityDeletion : "PreventRMEntityDeletion",
	Property_ReasonForClose : "ReasonForClose",
	Property_ReasonForExtract : "Reason",
	Property_ReasonForReclassification : "ReasonForReclassification",
	Property_ReceivedOn : "ReceivedOn",
	Property_RecordPattern : "RecordPattern",
	Property_RecordPatternIncrementedBy : "IncrementedBy",
	Property_RecordCategoryIdentifier : "RecordCategoryIdentifier",
	Property_RecordCategoryName : "RecordCategoryName",
	Property_RecordFolderIdentifier : "RecordFolderIdentifier",
	Property_RecordFolderName : "RecordFolderName",
	Property_RecordedDocuments : "RecordedDocuments",
	Property_RecordInformation : "RecordInformation",
	Property_RMReportTitle : "RMReportTitle",
	Property_ReportName : "ReportName",
	Property_RetainMetadata : "RetainMetadata",
	Property_Reviewer: "Reviewer",
	Property_RMEntityDescription : "RMEntityDescription",
	Property_RMRetentionTriggerPropertyName: "RMRetentionTriggerPropertyName",
	Property_RMRetentionPeriod: "RMRetentionPeriod",
	Property_RMExternallyManagedBy: "RMExternallyManagedBy",
	Property_SentOn : "SentOn",
	Property_Subject: "EmailSubject",
	Property_SupersededBy : "SupercedingRecords",
	Property_Supersedes : "SupercededBy",
	Property_To : "To",
	Property_TransferOrAccessionToNARAIndicator : "TransferOrAccessionToNARAIndicator",
	Property_VitalRecordDeclareDate : "VitalRecordDeclareDate",
	Property_VitalRecordDescription : "VitalRecordDescription",
	Property_VitalRecordDisposalTrigger : "VitalRecordDisposalTrigger",
	Property_VitalRecordNextReviewDate : "VitalRecordNextReviewDate",
	Property_VitalRecordReviewAction : "VitalRecordReviewAction",
	Property_VolumeName : "VolumeName",
	
	//Repository types
	RepositoryType_Plain : "Plain",
	RepositoryType_Content: "Content",
	RepositoryType_FilePlan: "FilePlan",
	RepositoryType_Combined: "Combined",
	
	//Retention Modes
	DispositionMode_SimpleRetention: "DispositionMode_SimpleRetention",
	DispositionMode_AdvancedRetention : "DispositionMode_AdvancedRetention",
	
	//ReportyEntryTypes
	ReportEntry_fileplan_browse : "fileplan_browse",
	ReportEntry_disposal_schedule : "disposal_schedule",
	ReportEntry_hold_name : "hold_name",
	ReportEntry_rm_entity_type : "rm_entity_type",
	ReportEntry_disposal_action_export : "disposal_action_export",
	ReportEntry_disposal_action : "disposal_action",	
	ReportEntry_user_name : "user_name",
	ReportEntry_report_type : "report_type",
	ReportEntry_ros_name : "ros_name",
	ReportEntry_ros_browse : "ros_browse",
	ReportEntry_action : "action",
	ReportEntry_review_decision : "review_decision",
	ReportEntry_application_type : "application_type",
	ReportEntry_fileplan_name : "fileplan_name",
	
	ReportEntry_DateTime_MaxValue: "9999-12-31",
	ReportEntry_DateTime_MinValue: "1752-12-31",
	ReportEntry_DateTime_Format : "M/d/yyyy",
	ReportEntry_Settability : "readWrite",
	ReportEntry_Param_StringType : "String",
	ReportEntry_Param_DateTimeType : "DateTime",
	
	ReportWindowNamePrefix : "ReportViewer",
	ReportDefinitionCopy : "Copy of ",

	//search
	Search_application: "IER",//"RM",
	Search_Document: "document",
	Search_Folder: "folder",
	Search_default_cbrPageSize : "50",
	Search_CBRType_Verity: "1",
	Search_CBRType_Cascade: "2",
	Search_CBR_Dynamic_Switching : "1",
	Search_CBR_QueryRankOverride_Required : "2",
	
	//services
	Service_CreateFilePlan : "ierCreateFilePlanService",
	Service_CloseRecordContainer : "ierCloseRecordContainerService",
	Service_CreateSimpleDispositionSchedule : "ierCreateSimpleDispositionScheduleService",
	Service_CreateRecordCategory : "ierCreateRecordCategoryService",
	Service_CreateRecordFolder : "ierCreateRecordFolderService",
	Service_CreateRecordVolume : "ierCreateRecordVolumeService",
	Service_EditFilePlan : "ierEditFilePlanService",
	Service_EditRecordContainer : "ierEditRecordContainerService",
	Service_CreateAction : "ierCreateActionService",
	Service_CreateTrigger : "ierCreateTriggerService",
	Service_Declare : "ierDeclareRecordService",
	Service_FileRecord : "ierFileRecordService",
	Service_GetChoiceList : "ierGetChoiceListService",
	Service_GetConditionResults : "ierGetConditionResults",
	Service_GetObjects : "ierGetObjectsService",
	Service_GetDispositionSchedules : "ierGetDispositionSchedules",
	Service_GetEntityNameFromNamingPattern : "ierGetEntityNameFromNamingPattern",
	Service_GetFilePlans : "ierGetFilePlans",
	Service_GetFilePlanRepositoriesFromDesktop : "ierGetFilePlanRepositoriesFromDesktop",
	Service_GetObjectConditions : "ierGetObjectConditions",
	Service_GetNamingPatternLevels : "ierGetNamingPatternLevels",
	Service_GetQuickSearchResults : "ierGetQuickSearchResults",
	Service_GetReportDefintions : "ierGetReportDefinitions",
	Service_GetRecordEntryTemplates : "ierGetRecordEntryTemplates",
	Service_GetRepositoryAttributes : "ierGetRepositoryAttributes",
	Service_MoveRecord :"ierMoveRecordService",
	Service_EditRecord :"ierEditRecordService",
	Service_OpenRecordEntryTemplate : "ierOpenRecordEntryTemplate",
	Service_ReopenRecordContainer : "ierReopenRecordContainerService",
	Service_SaveHold : "ierSaveHoldService",
	Service_SaveLocation : "ierSaveLocationService",
	Service_SaveNamingPattern: "ierSaveNamingPatternService",
	Service_SaveSystemConfigurations: "ierSaveSystemConfigurationsService",
	Service_ScheduleReportService: "ierScheduleReportService",
	Service_Delete : "ierDeleteService",
	Service_Relocate : "ierRelocateRecordContainerService",
	Service_ReRunReport: "ierReRunReport",
	Service_RunReport : "ierRunReport",
	Service_PlaceOnHold : "ierPlaceOnHoldService",
	Service_RemoveHold : "ierRemoveHoldService",
	Service_GetEntitiesOnHold : "ierGetEntitiesOnHoldService",
	Service_CopyRecord : "ierCopyRecordService",
	Service_Copy : "ierCopyService",
	Service_LinkRecord : "ierLinkRecordService",
	Service_GetAndSavePluginConfiguration : "ierGetAndSavePluginConfiguration",
	Service_Undeclare : "ierUndeclareService",
	Service_GetDocumentInfo : "ierGetDocumentInfoService",
	Service_DynamicHoldRequstService : "ierDynamicHoldRequestService",
	Service_GetHistory : "ierGetHistoryService",
	Service_GetReportResult: "ierGetReportResult",
	Service_GetAssociatedContentRepositories: "ierGetAssociatedContentRepositories",
	Service_DeleteReportResults : "ierDeleteReportResults",
	Service_ValidateNamingPattern : "ierValidateNamingPattern",
	Service_GetTaskManagerTasks : "ierGetTaskManagerTasks",
	Service_GetNextVolumeName : "ierGetNextVolumeNameService",
	Service_GetHoldsForEntity : "ierGetHoldsForEntityService",
	Service_RescheduleTask: "ierRescheduleTaskService",
	Service_DeleteTask: "ierDeleteTaskService",
	Service_TerminateTask: "ierTerminateTaskService",
	Service_ResumeTask: "ierResumeTaskService",
	Service_PauseTask: "ierPauseTaskService",
	Service_GetExecutionRecords: "ierGetExecutionRecordsService",
	Service_SaveReportDefinition : "ierSaveReportDefinitionService",
	Service_RetrieveLinks: "ierRetrieveLinksOnEntityService",
	Service_GetRecordFromDeclaredDocument : "ierGetRecordFromDeclaredDocumentService",
	Service_GetAllRecordProperties: "ierGetAllRecordPropertiesService",
	Service_CreateIERDesktop: "ierCreateDesktopService",
	Service_GetObjectStoreSecurity: "ierGetObjectStoreSecurity",
	Service_ObjectStoreSecurity: "ierObjectStoreSecurity",
	Service_GetRepositoryPermissions: "ierGetRepositoryPermissions",
	
	SchedulePropagation_None: "0",
	SchedulePropagation_ToAllInheritingEntities: "1",
	SchedulePropagation_ToImmediateSubContainersAndInheritingEntities: "2",
	SchedulePropagation_ToAllNonAssignedSubContainers: "3",

	//Real Search Principal Attribute
	PrincipalSearchAttribute_DisplayName : "2",
	PrincipalSearchAttribute_ShortName : "1",
	PrincipalSearchAttribute_None : "0",
	
	//Task Status
	TaskStatus_InProgress : "16",
	TaskStatus_Init : "2",
	TaskStatus_Pending : "4",
	TaskStatus_Completed : "32",
	TaskStatus_Scheduled : "256",
	TaskStatus_Failed : "128",
	TaskStatus_Paused : "64",
	TaskStatus_Recurring : "-1",
	
	TaskType_Report : "Report",
	TaskType_DispositionSweep : "DispositionSweep",
	TaskType_HoldSweep : "HoldSweep",
	TaskType_DefensibleDisposal : "DefensibleDisposal",
	
	TaskType_ReportClass : "com.ibm.ier.plugin.tasks.RunReportTask",
	TaskType_DispositionSweepClass : "com.ibm.ier.plugin.tasks.RunDispositionSweepTask",
	TaskType_HoldSweepClass : "com.ibm.ier.plugin.tasks.RunHoldSweepTask",
	TaskType_DDConversionClass : "com.ibm.ier.plugin.tasks.ConvertToDefensibleDisposalContainerTask",
	TaskType_DDReportSweepClass : "com.ibm.ier.plugin.tasks.RunDefensibleDisposalReportSweepTask",
	
	TaskCategories_AllTasks : "AllTasks",
	TaskCategories_ScheduledTasks : "ScheduledTasks",
	TaskCategories_RecurringTasks : "RecurringTasks",
	TaskCategories_FailedTasks : "FailedTasks",
	TaskCategories_PausedTasks : "PausedTasks",
	TaskCategories_InProgressTasks : "InProgressTasks",
	TaskCategories_CompletedTasks : "CompletedTasks",
	TaskCategories_ReportTasks : "ReportTasks",
	TaskCategories_DefensibleDisposalTasks: "DefensibleDisposalTasks",
	TaskCategories_HoldSweepTasks : "HoldSweepTasks",
	
	WorkflowType_BasicSchedule: "Basic Schedule",

	// Application Type
	ApplicationTypes : [
	                    "text/html",
	                    "application/octet-stream",
	                    "application/msword",
	                    "application/mspowerpoint",
	                    "application/powerpoint",
	                    "image/pjpeg",
	                    "image/jpeg",
	                    "image/gif",
	                    "application/pdf",
	                    "text/plain",
	                    "application/xml",
	                    "text/xml",
	                    "video/avi",
	                    "image/bmp",
	                    "image/x-windows-bmp",
	                    "application/excel",
	                    "application/vnd.ms-excel",
	                    "application/x-excel"
	                    ],
	
	
	
	nop: null
});

var constants = new _Constants();

return constants;
});
